### ISSUE TITLE
Esc key

### ISSUE THREAD

**Issue by BergerKing424** [HiKay/TouchBarDisabler#1]
Hello, I want to start by saying thank you, this app is fantastic!  I find the touchbar really annoying.  At any rate, I am submitting an "issue" but it's really a feature request...there is Esc key now that the touchbar is disabled and no Esc shortcut.  Please let me know if I'm missing something.  Thank you again!

**Comment by HiKay** [comment]
You can remap the Caps Lock Key to work as the Escape key in System Preferences -> Keyboard -> Modifier Keys. Here's a few screenshots about the process.

<img width="780" alt="System Preferences" src="https://cloud.githubusercontent.com/assets/20536283/25677507/3d7e27ae-3014-11e7-8a2f-789686b48369.png">

<img width="780" alt="Modifier Keys" src="https://cloud.githubusercontent.com/assets/20536283/25677528/5386a15c-3014-11e7-9d02-cae6264fe0de.png">

<img width="780" alt="Remapping Caps Lock Key as Escape Key" src="https://cloud.githubusercontent.com/assets/20536283/25677445/faf968c6-3013-11e7-95b8-106229685cea.png">

**Comment by dbquarrel** [comment]
Sorry but your app is nearly useless if you don't support the ESC key. 

This is one of the primary built in flaws of the touchbar, that it removes this key from the keyboard. By removing the ESC key from the touchbar, you are making a bad decision worse. 

Telling users to remap the caps lock key to escape is the same kind of bad approach that apple is already using. 

If the goal of your software is to fix apple's bad decisions, you should not be in competition with them over further bad decisions.

The control key traditionally has been where the capslock key is now. So a lot of us have already put the control key back there. Also, we have no desire to re-learn how to touchtype after 30 years.

This is a good feature request to put the ESC key in place on the touchbar. I was initially excited to see your application, downloaded it, now I'm deleting it because it's worse than useless to remove the ESC key completely from the keyboard.

**Comment by dbquarrel** [comment]
Dragos, I'm so sorry that I offended your gentle sensibilities by being honest and direct. 

I'm not asking for a feature.

I'm telling him the truth about his app, which I don't use, because of the tragic flaw. This forum is for feedback, which I've given. 

 Perhaps you should avoid the internet if you are so easily shaken by clear and direct feedback.

**Comment by DragosRotaru** [comment]
Hey dbquarrel,

Your problem has nothing to do with TouchBarDisabler missing a convenient
escape key – your problem is that you are a shitty person. Unfortunately
for you, there is no escape key in the world that will help you with that.

Have a great day,
Dragos Rotaru


On Mar 16, 2018 1:59 PM, "dbquarrel" <notifications@github.com> wrote:

Dragos, I'm so sorry that I offended your gentle sensibilities by being
honest and direct.

I'm not asking for a feature.

I'm telling him the truth about his app, which I don't use, because of the
tragic flaw. This forum is for feedback, which I've given.

Perhaps you should avoid the internet if you are so easily shaken by clear
and direct feedback.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LumingYin/TouchBarDisabler/issues/1#issuecomment-373796172>,
or mute the thread

**Comment by dbquarrel** [comment]
lol, there is medication for what you are experiencing Dragos.

**Comment by DragosRotaru** [comment]
And I drink a few cases of it every night 🍺

Unfortunately, they haven't found a medication for your condition yet.

Thanks for the banter dbquarrel, its been fun but I gotta get some work done.

**Comment by dbquarrel** [comment]
maybe if you laid off the booze you'd be less irritable.

**Comment by stemwinder** [comment]
👆The Internet, in one thread.

**Comment by lfritts** [comment]
LumingYin:  Thank you for excellent app.  I am a coder and I have all sorts of problems with the stupid esc key in the touchbar.  You have saved me many hours of work.  

One other comment: There have been and will always be people that feel the only way to prove to people they are intelligent and relevant is by pointing out what they believe to be flaws in something they don't event use or believe in.  Unfortunately, that only proves the they are the opposite and should be ignored entirely.

**Comment by dbquarrel** [comment]
@lfritts  

I think there good sir you have your logic backwards.

The reasons that some people do not use a certain tool is because the tool has flaws for which it prevents them from using the tool. It is not attacking the developer to point out areas in which the tool is falling short, nor is github issue reports a place to come in and place your fawning love of the app. @LumingYin is an adult and technically skilled and he will either react with code or else ignore the suggestions, that's it.

As a coder you should understand, in order to expand the use case of the tools, you need to then criticize the tool, so that the flaws in the tool can be addressed and then the use case for the tool expanded to a greater pool of users.

The problem is, that somehow, new programmers coming online in the snowflake generation confuse criticism of software with criticism of efforts or of a person. Then, these same snowflake generation people become outraged on behalf of other people. This outrage turns around and vents as personal attacks, rather than attacks on what was said: criticism of the tool.

Without criticism, nothing can improve.

This has been lost on an entire generation of participation-award winners, and gold star receivers, for arriving at school and breathing through their mouths.

If the developer is not outraged, there is no need to be outraged on their behalf because it means you probably misunderstood.

Furthermore, telling the developer of software to reject and ignore comments that are critical of their software is something that doesn't allow them to understand areas of improvement. Where software leaves the lab and hits the real world, that's where you get feedback that lets you polish it and change things that do matter to your users.

This is not a painting he's made in crayon for hanging on his mom's fridge and the "how dare you" outrage that comes from certain people who are using this, I have a lot of trouble understanding other than that you've just got a gold star on your forehead for showing up at school.

Also I am not going to fill my criticism with a bunch of insincere fawning and ass kissing just because it's going to otherwise hurt the feelings of readers who belong to the outrage generation. The developer is clearly not one of you.

With my part said, you outragers have nothing to bring to the conversation except for your emotional reactions and your outrage and hate, as well as your lack of reading comprehension. As such, it's those contributions in particular that water down what's basically a bug report and design enhancement requests that the developer can read and choose to ignore, and fills a technical forum with your feelings, which absolutely do not matter whatsoever.

So I will mute this now so I don't have to read any more of this snowflake stupidity, from people with egos so fragile now that they cannot even read a bug report without pointing their shaking finger and screaming "for shame" while spit flies out of their mouths. So I will return you to your mouth breathing and wish you sir, GOOD DAY.

**Comment by normanzb** [comment]
Just want to leave it and hopefully it might help some people:

If you happen to use one of the British keyboard, you might want to map the `section key §` into escape with below command as it feels very natural to reach the top left corner to `escape`:

```
echo "Mapping § to Escape"
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x700000064,"HIDKeyboardModifierMappingDst":0x700000029}]}'
```

and then you can make the mapping script auto start with the system by:
```
sudo defaults write com.apple.loginwindow LoginHook ~/Scripts/mapSectionSignAsEsc.sh
```

And then use TouchbarToggler to disable the touch bar.
Unfortunately for me the TouchbarToggler doesn't work with my 2018 mbp tho...
